import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Providers } from "./providers"
import { Box, Container } from "@chakra-ui/react"
import Header from "./_components/Header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Civilaw",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <title>Civilaw</title>
        <link rel="icon" href="/images/favicon.svg" />
      </head>
      <body className={inter.className}>
        <Providers>
          <Box bg="#EDF0F7">
            <Header />

            <Container maxW="1200px" mx="auto" p={4} mt={4}>
              <Box as="main" bg="#FFFFFF" p="32px">
                {children}
              </Box>
            </Container>
          </Box>
        </Providers>
      </body>
    </html>
  )
}
